### ISSUE TITLE
Does process exit code 2 really means virus?

### ISSUE THREAD

**Issue by zeecorleone** [jitbit/WinDefender#1]
@alex-jitbit  I just rant his against few files, and process exit code is always `2`. What does exit code "2" really mean? Documentation (if I was looking at the right one [here](https://learn.microsoft.com/en-gb/windows/win32/debug/system-error-codes--0-499-)), says it means something like "system couldn't find the specified file". Can you clarify on this point, how can correctly use your implementation of virus scan.

**Comment by alex-jitbit** [comment]
You're looking at system error codes, not process return codes. The error code 2 is thrown when the file contains a virus (which is confirmed by a unit test I have here, for an EICAR file https://en.wikipedia.org/wiki/EICAR_test_file)
